DROP TABLE IF EXISTS attendees;
DROP TABLE IF EXISTS talks;
DROP TABLE IF EXISTS conferences;
DROP TABLE IF EXISTS edits;

DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TYPE IF EXISTS attendee_type;

DROP TYPE IF EXISTS edit_type;